OnlineFoodDelivery/Controllers/CancelSpecificOrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineFoodDelivery.Models;

namespace OnlineFoodDelivery.Controllers
{
    public class CancelSpecificOrderController : Controller
    {
        private readonly OnlineFoodDeliveryEntities db = new OnlineFoodDeliveryEntities();

        // GET: CancelSpecificOrder
        public ActionResult Index()
        {
            var orders = db.orders.Include(o => o.product);
            return View(orders.ToList());
        }

       
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                order order = db.orders.Find(id);
                if (order == null)
                {
                    return HttpNotFound();
                }
                return View(order);
            }
            catch (Exception ex)
            {
                ViewBag.Message(ex.Message);
            }
            return View();
        }

        // POST: CancelSpecificOrder/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                order order = db.orders.Find(id);
                db.orders.Remove(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message(ex.Message);
            }
            return View();
        }
    }
}

OnlineFoodDelivery/Controllers/CustomersDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineFoodDelivery.Models;

namespace OnlineFoodDelivery.Controllers
{
    public class CustomersDetailsController : Controller
    {
        private readonly OnlineFoodDeliveryEntities db = new OnlineFoodDeliveryEntities();

        // GET: CustomersDetails
        public ActionResult Index()
        {
            return View(db.customers.ToList());
        }

        // GET: CustomersDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }
    }
}

OnlineFoodDelivery/Controllers/LoginController.cs
using OnlineFoodDelivery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineFoodDelivery.Controllers
{
    public class LoginController : Controller
    {
        private readonly OnlineFoodDeliveryEntities db = new OnlineFoodDeliveryEntities();
        public ActionResult LoginPage ()
        {
            return View();
        }
        public ActionResult AdminLogin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AdminLogin(admin admin)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Check if the admin exists in the database
                    var existingAdmin = db.admins.FirstOrDefault(a => a.username == admin.username && a.password == admin.password);

                    if (existingAdmin != null)
                    {
                        // Successfully logged in, redirect to Admin dashboard
                        return RedirectToAction("AdminDashboard", "Admin");
                    }
                    else
                    {
                        // If the credentials are incorrect
                        ViewBag.ErrorMessage = "Invalid username and password";
                        return View(admin);
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message(ex.Message);
            }
            // If the model state is not valid, return to the login view
            return View(admin);
        }

        //userlogin
        public ActionResult CustomerLogin() => View();
        [HttpPost]
        public ActionResult CustomerLogin(string username, string password)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var user = db.customers.SingleOrDefault(u => u.username == username && u.password == password);
                    if (user != null)
                    {
                        Session["customerid"] = user.customerid;
                        return RedirectToAction("CustomerDashboard", "Customer");
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Invalid login credentials";
                        return View();
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message(ex.Message);
            }
            return View();
        }
        public ActionResult CustomerRegister() => View();

        [HttpPost]
        public ActionResult CustomerRegister(customer customer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.customers.Add(customer);
                    db.SaveChanges();
                    return RedirectToAction("CustomerLogin");
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message(ex.Message);
            }
            return View(customer);
        }
    }
}

OnlineFoodDelivery/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineFoodDelivery.Models;

namespace OnlineFoodDelivery.Controllers
{
    public class ProductsController : Controller
    {
        private readonly OnlineFoodDeliveryEntities db = new OnlineFoodDeliveryEntities();

        // GET: Products
        public ActionResult Index()
        {
            return View(db.products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "productid,productname,description,price")] product product)
        {
            if (ModelState.IsValid)
            {
                db.products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "productid,productname,description,price")] product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            product product = db.products.Find(id);
            db.products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineFoodDelivery/Views/Admin/AdminDashboard.cshtml
@{
    ViewBag.Title = "AdminDashboard";
}
<style>
    .container-fluid {
        background-image: url('../../images/admindashboard.jpg');
        background-repeat: no-repeat;
        /*background-position:center;*/
        height: 1500px;
        width: 900px;
        margin-top: -10px;
        margin-left: 100px;
        background-size: 900px 500px;
    }

    .list-group-item {
        margin-left: 100px;
        font-family: 'Lucida Sans';
    }

    h4 {
        color: azure;
        margin-left:100px;
    }
    .div1 {
        margin-top: -10px;
        margin-left: 700px;
        display: inline-block;
        padding: 4px 8px;
        font-size: 24px;
        cursor: pointer;
        text-align: center;
        text-decoration: none;
        outline: none;
        color: #fff;
        background-color: #04AA6D;
        border: none;
        border-radius: 10px;
        box-shadow: 0 8px #999;
    }
</style>
<div class="container-fluid">
    <br /><br />
    <h4>Admin Dashboard</h4>
    <br />
    <div class="row">
        <div class="col-md-4">

            <ul class="list-group-horizontal">
                <li class="list-group-item  mt-4">
                    @Html.ActionLink("Add FoodItems", "Index", "Products", null, new { @class = "btn btn-outline-primary btn-sm" })
                </li>
                <li class="list-group-item  mt-1">
                    @Html.ActionLink("Edit FoodItems", "Index", "Products", null, new { @class = "btn btn-outline-info btn-sm" })
                </li>
                <li class="list-group-item  mt-1">
                    @Html.ActionLink("Delete FoodItems", "Index", "Products", null, new { @class = "btn btn-outline-success btn-sm" })
                </li>
                <li class="list-group-item mt-1">
                    @Html.ActionLink("Show FoodItems", "Index", "Products", null, new { @class = "btn btn-outline-warning btn-sm" })
                </li>
            </ul>
        </div>
        <div class="col-md-6">

            <ul class="list-group-horizontal">
                <li class="list-group-item mt-4">
                    @Html.ActionLink("Orders Received", "Index", "OrdersReceivedFromCustomer", null, new { @class = "btn btn-outline-secondary btn-sm" })
                </li>
                <li class="list-group-item mt-1">
                    @Html.ActionLink("Customers Details", "Index", "CustomersDetails", null, new { @class = "btn btn-outline-danger btn-sm" })
                </li>
                <li class="list-group-item mt-1">
                    @Html.ActionLink("Cancel Specific Order", "Index", "CancelSpecificOrder", null, new { @class = "btn btn-outline-light btn-sm" })
                </li>
            </ul>
        </div>
    </div>
    <div class="div1">
        @Html.ActionLink("Logout", "AdminLogin", "Login", null, new { @class = "btn btn-outline-danger btn-sm" })
    </div>
</div>