OnlineFoodDelivery/Controllers/CancelOrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineFoodDelivery.Models;

namespace OnlineFoodDelivery.Controllers
{
    public class CancelOrderController : Controller
    {
        private readonly OnlineFoodDeliveryEntities db = new OnlineFoodDeliveryEntities();

        // GET: CancelOrder
        public ActionResult Index()
        {
            return View(db.orders.ToList());
        }
        // GET: CancelOrder/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                order order = db.orders.Find(id);
                if (order == null)
                {
                    return HttpNotFound();
                }
                return View(order);
            }
            catch (Exception ex)
            {
                ViewBag.Message(ex.Message);
            }
            return View();
        }

        // POST: CancelOrder/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                order order = db.orders.Find(id);
                db.orders.Remove(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message(ex.Message);
            }
            return View();
        }

    }
}

OnlineFoodDelivery/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineFoodDelivery.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult CustomerDashboard()
        {
            return View();
        }
    }
}

OnlineFoodDelivery/Views/CancelOrder/Delete.cshtml
@model OnlineFoodDelivery.Models.order

@{
    ViewBag.Title = "Delete";
}
<style>
    body {
        background-image: url('../../images/fff.jpg');
        background-position: center;
        background-repeat: no-repeat;
        background-size: 1200px 900px;  
    }
    .container-fluid{
        margin-left:500px;
       width:500px;
        background-color:aliceblue;
    }
</style>
<body>
    <div class="container-fluid">
        <h4>Are you sure you want to delete this?</h4>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.productid)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.productid)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.product.productname)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.product.productname)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.quantity)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.quantity)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.amount)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.amount)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.DeliveryAddress)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DeliveryAddress)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.paymentmethod)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.paymentmethod)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.cardnumber)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.cardnumber)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.cardholdername)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.cardholdername)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.cvv)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.cvv)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.expirydate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.expirydate)
                </dd>
            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-outline-success" /> |
            @Html.ActionLink("Back", "Index", "CancelOrder", null, new { @class = "btn btn-outline-primary btn-md" })
        </div>
            }
        </div>
        <br /><br />
    </div>
</body>

OnlineFoodDelivery/Views/CancelOrder/Index.cshtml
@model IEnumerable<OnlineFoodDelivery.Models.order>

@{
    ViewBag.Title = "Index";
}
<style>
    body {
        background-image: url('../../images/foodbackimg.jpg');
        background-repeat: no-repeat;
        height: 1500px;
        width: 1000px;
        margin-top: -20px;
       /* margin-left: 150px;*/
        background-size: 1500px 650px;
    }

    .table {
        background-color: lavenderblush;
    }
    h2{
        color:darkturquoise;
    }
</style>
<body>

    <h2>Cancel Order</h2>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.orderid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.productid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product.productname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeliveryAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.paymentmethod)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cardnumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cardholdername)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cvv)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.expirydate)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.orderid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.productid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.product.productname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DeliveryAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.paymentmethod)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cardnumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cardholdername)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cvv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.expirydate)
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.orderid }, new { style = "color:crimson;" })
                </td>
            </tr>
        }
    </table>
    @Html.ActionLink("Back", "CustomerDashboard", "Customer", null, new { @class = "btn btn-outline-light btn-sm" })
</body>