OnlineFoodDelivery/Models/addtocart.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodDelivery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class addtocart
    {
        public int cartid { get; set; }
        public Nullable<int> productid { get; set; }
        [Required(ErrorMessage = "quantity is required")]
        public Nullable<int> quantity { get; set; }
        public Nullable<double> amount { get; set; }
       
        public virtual product product { get; set; }

        internal static decimal Sum(Func<object, object> value)
        {
            throw new NotImplementedException();
        }
    }
}

OnlineFoodDelivery/Controllers/AddtocartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineFoodDelivery.Models;

namespace OnlineFoodDelivery.Controllers
{
    public class AddtocartsController : Controller
    {
        private readonly OnlineFoodDeliveryEntities db = new OnlineFoodDeliveryEntities();

        // GET: Addtocarts
        public ActionResult Index()
        {
            var addtocarts = db.addtocarts.Include(a => a.product);
            return View(addtocarts.ToList());
        }

        
        public ActionResult Create()
        {
            ViewBag.productid = new SelectList(db.products, "productid", "productname");
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "cartid,productid,quantity,amount")] addtocart addtocart)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.addtocarts.Add(addtocart);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.productid = new SelectList(db.products, "productid", "productname", addtocart.productid);
                return View(addtocart);
            }
            catch (Exception ex)
            {
                ViewBag.Message(ex.Message);
            }
            return View();
            
        }

        // GET: Addtocarts/Edit/5
        
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                addtocart addtocart = db.addtocarts.Find(id);
                if (addtocart == null)
                {
                    return HttpNotFound();
                }
                return View(addtocart);
            }
            catch (Exception ex)
            {
                ViewBag.Message(ex.Message);
            }
            return View();
        }

        // POST: Addtocarts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                addtocart addtocart = db.addtocarts.Find(id);
                db.addtocarts.Remove(addtocart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message(ex.Message);
            }
            return View();
        }
        public ActionResult Index1()
        {
            var cartItems = db.addtocarts.Include("Product").ToList();
            return View(cartItems);
        }

        // Method to add/update cart item
        [HttpPost]
        public ActionResult AddToCart(int productid, int quantity)
        {
            try
            {
                // Fetch the product price
                var product = db.products.Find(productid);
                if (product == null)
                {
                    return HttpNotFound();
                }

                // Calculate total amount
                int totalAmount = (int)(product.price * quantity);

                // Check if item already exists in cart
                var cartItem = db.addtocarts.SingleOrDefault(ci => ci.productid == productid);
                if (cartItem != null)
                {
                    // Update quantity and amount if item exists
                    cartItem.quantity += quantity;

                    cartItem.amount = product.price * cartItem.quantity;
                }
                else if (cartItem.quantity != null)
                {

                    cartItem.quantity -= quantity;
                    cartItem.amount = cartItem.quantity * product.price;
                    db.addtocarts.Remove(cartItem);
                }


                else
                {
                    // Add new item to cart
                    cartItem = new addtocart
                    {
                        productid = productid,
                        quantity = quantity,
                        amount = totalAmount
                    };
                    db.addtocarts.Add(cartItem);
                }

                db.SaveChanges();
                return RedirectToAction("Index"); // Redirect to your cart index or another view
            }
            catch (Exception ex)
            {
                ViewBag.Message(ex.Message);
            }
            return View();
        }

        // Optionally, you can add a method to remove items from the cart
        public ActionResult RemoveFromCart(int cartItemId)
        {
            try
            {
                var cartItem = db.addtocarts.Find(cartItemId);
                if (cartItem != null)
                {
                    db.addtocarts.Remove(cartItem);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message(ex.Message);
            }
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineFoodDelivery/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineFoodDelivery.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult CustomerDashboard()
        {
            return View();
        }
    }
}

OnlineFoodDelivery/Views/Addtocarts/Create.cshtml
@model OnlineFoodDelivery.Models.addtocart

@{
    ViewBag.Title = "Create";
}
<style>
    body {
        background-image: url('../../images/addtocart1.jpg');
        background-repeat: no-repeat;
        height: 1500px;
        width: 1000px;
        margin-top: -20px;
        margin-left: 50px;
        background-size: 1300px 650px;
    }

    .form-group {
        color: bisque;
    }

    h4 {
        color: bisque;
    }
</style>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>addtocart</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.productid, "productid", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("productid", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.productid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.amount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
                </div>
            </div>
            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Add to cart" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to AddtoCart List", "Index")
    </div>
</body>

OnlineFoodDelivery/Views/Addtocarts/Delete.cshtml
@model OnlineFoodDelivery.Models.addtocart

@{
    ViewBag.Title = "Delete";
}

<style>
    body {
        background-image: url('../../images/addtocart2.jpg');
        background-repeat: no-repeat;
        height: 1500px;
        width: 1000px;
        margin-top: -20px;
        margin-left: 50px;
        background-size: 1300px 650px;
    }

    .form-group {
        color: bisque;
    }

    h4 {
        color: bisque;
    }
</style>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.quantity)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.quantity)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.amount)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.amount)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.product.productname)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.product.productname)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>

OnlineFoodDelivery/Views/Addtocarts/Index.cshtml
@model IEnumerable<OnlineFoodDelivery.Models.addtocart>

@{
    ViewBag.Title = "Index";
}
<style>
    body {
        background-image: url('../../images/addtocart.jpg');
        background-repeat: no-repeat;
        height: 1500px;
        width: 1000px;
        margin-top: -20px;
        margin-left: 50px;
        background-size: 1300px 650px;
    }

    .table {
        background-color: lavender;
    }

    p {
        color: aquamarine;
    }
</style>
<body>
    <h4>Add to cart</h4>

    <p>
        @Html.ActionLink("Add To Cart", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.cartid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.productid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product.productname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.amount)
            </th>

            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.cartid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.productid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.product.productname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.amount)
                </td>

                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = item.cartid }, new { style = "color:red;" })
                </td>
                <td>
                    @Html.ActionLink("Click here to increment quantity", "Index1", "Addtocarts", null, new { @class = "btn btn-outline-primary btn-sm" })
                </td>
            </tr>
        }

    </table>

    @Html.ActionLink("Back", "CustomerDashboard", "Customer", null, new { @class = "btn btn-outline-secondary btn-sm" })
</body>

OnlineFoodDelivery/Views/Addtocarts/Index1.cshtml
@{
    ViewBag.Title = "Index1";
}

@model IEnumerable<OnlineFoodDelivery.Models.addtocart>

@{
    ViewBag.Title = "Index1";
}
<style>
    body {
        background-image: url('../../images/addtocart.jpg');
        background-repeat: no-repeat;
        height: 1500px;
        width: 1000px;
        margin-top: -20px;
        margin-left: 50px;
        background-size: 1300px 650px;
    }

    .table {
        background-color: lavender;
    }

    p, h2 {
        color: aquamarine;
    }
</style>
<body>
    <h2>Your Cart</h2>

    <table class="table">
        <thead>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Amount</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.product.productname</td>
                    <td>@item.quantity</td>
                    <td>@item.amount.ToString()</td>
                    <td>
                        @Html.ActionLink("Remove", "RemoveFromCart", new { cartItemId = item.cartid })
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <h3>Available Products</h3>
    @foreach (var product in Model.Select(i => i.product).Distinct())
    {
        <div>
            <h4>@product.productname</h4>
            <p>Price: @product.price.ToString()</p>
            <form action="@Url.Action("AddToCart", "Addtocarts")" method="post">
                <input type="hidden" name="productId" value="@product.productid" />
                <label>Quantity:</label>
                <input type="number" name="quantity" min="1" value="1" />
                <button type="submit">Add to Cart</button>
            </form>
        </div>
    }
</body>