OnlineFoodDelivery/Controllers/AdminController.cs
using OnlineFoodDelivery.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineFoodDelivery.Controllers
{
    public class AdminController : Controller
    {
       // private readonly OnlineFoodDeliveryEntities db = new OnlineFoodDeliveryEntities();
        // GET: Admin
        public ActionResult AdminDashboard()
        {
            return View();
        }
    }
}

OnlineFoodDelivery/Controllers/CustomersDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineFoodDelivery.Models;

namespace OnlineFoodDelivery.Controllers
{
    public class CustomersDetailsController : Controller
    {
        private readonly OnlineFoodDeliveryEntities db = new OnlineFoodDeliveryEntities();

        // GET: CustomersDetails
        public ActionResult Index()
        {
            return View(db.customers.ToList());
        }

        // GET: CustomersDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            customer customer = db.customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }
    }
}

OnlineFoodDelivery/Views/CustomersDetails/Details.cshtml
@model OnlineFoodDelivery.Models.customer

@{
    ViewBag.Title = "Details";
}
<style>
    body {
        background-image: url('../../images/foodlist.jpg');
        background-repeat: no-repeat;
        background-position: center;
        height: 700px;
        width: 1000px;
    }

    .dl-horizontal {
        margin-left: 500px;
    }

    p {
        margin-left: 500px;
    }

    h2 {
        margin-left: 500px;
    }
</style>
<h2>Details</h2>

<div>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fullname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fullname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emailid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emailid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phonenumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phonenumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.pincode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.pincode)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back", "Index", "CustomersDetails", null, new { @class = "btn btn-success btn-sm" })
</p>

OnlineFoodDelivery/Views/CustomersDetails/Index.cshtml
@model IEnumerable<OnlineFoodDelivery.Models.customer>

@{
    ViewBag.Title = "Index";
}
<style>
    body {
        background-image: url('../../images/foodyimg.jpg');
        background-repeat:no-repeat;
        height: 1500px;
        width: 1000px;
        margin-top: -20px;
        margin-left: 150px;
        background-size: 1300px 650px;
    }
    .container-fluid {
        background-color: lightgoldenrodyellow;
    }
    p{
        margin-left:150px;
    }
</style>
<body>
    <div class="container-fluid">
        <h2>Customers Details</h2>
        <hr />
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.customerid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.username)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.fullname)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.emailid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.phonenumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.pincode)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.customerid)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.username)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.fullname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.emailid)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.phonenumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.pincode)
                    </td>
                    <td>
                            @Html.ActionLink("Details", "Details", new { id = item.customerid},new { style = "color:crimson;" })
                    </td>
                </tr>
             }
        </table>
        <br />
    </div>
    <br />
    <p>
        @Html.ActionLink("Back", "AdminDashboard", "Admin", null, new { @class = "btn btn-outline-danger btn-sm" })
    </p>
</body>